### PR TITLE
another fix of repositories not alwawys deleted

### PR DESCRIPTION
**Pull request by bydga**
so what do you think of this? :)

### CODE REVIEW

**Comment by kwk** [comment]
I'm going to need some time for this to review not because it is complicated but I have other regular work to do...

**Comment by bydga** [comment]
ping.

**Comment by kwk** [comment]
Sorry, but I will work on it when I find the time.

**Comment by bydga** [comment]
rebased and added one commit solving the routing. However i really can't test it. npm install-ing inside the docker (on osx via docker-machine) takes hours to process (thanks to all those grunt-xx deps)..

Ideally -  as a future enhancment - get rid of the stupid apache and replace it with express.js :) It will be much more lightweight and local testing (on every OS) would be just running `node app/server.js`  Also your dockerfile would be much simpler as you will not need to run the initd apache..

**Comment by kwk** [comment]
@bydga thank you. But if you cannot test it, I'll have to do it. It looks good so far except that it should be `repositories` rather than `/repositories`. About express.js: If you can tell me how to do proying, SSL, and Kerberos authentication with it. I'd feel happy to use it. So please, create a gist or something as a good starting point. I tried nginx before apache and stopped using it because of lack of Kerberos support.

**Comment by bydga** [comment]
there you are :) https://github.com/bydga/express-proxy-kerberos

I havent tested the kerb auth though, because i have no kerberos server available. But passport is a surely a great module for authenticating nodejs app. Maybe sending some appropriate header in the express middleware could trigger the http basic auth (like i think the apache mod_kerb does).

**Comment by xiaods** [comment]
+1, current hub.docker tag v2 always can't delete images with this bug. please consider review it asap. can't wait to use it enhance.

**Pull request closed without merging**
