### PR TITLE
Support for Basic Authentiocation added. Users need to set ENV_AUTH_USE_BASIC and volume for htpasswd

### PR DESCRIPTION
**Pull request by rexberg**
Enable Apache "Basic Authentication" for repo/tags management in the registry UI. It also enables "Basic Authentication" for everything except "GET" methods against the registry.

### CODE REVIEW

**Comment by HeadlessChild** [comment]
>Why do you limit basic auth only to GET requests?
I limit everything except GET requests. So users without "Basic Authentication" should only be able to access GET requests. Users that authenticate with "Basic Authentication" are able to access all requests.

**Comment by kwk** [comment]
Sorry about that mistake of mine.
The more I think about this I dislike the fact that I have to care about all scenarios everybody has. Next day somebody want to authenticate against AD. Even though basic auth is ... well ... basic, maybe this is a good time to think about another approach for dealing with authentication and authorization and such. Having apache run inside the container was just my first idea and it felt rather comfortable.

Now, I think that authentication should be done in another container, that forwards to the docker-registry-frontend internally. If you don't expose the docker-registry-frontend, then there's no security issue and you can do whatever auth you want.

**Comment by HeadlessChild** [comment]
Okay I can see that it might be a problem.
I'm just seeing it as additional features that's optional for users to use. I have even thought about adding LDAP authentication but that might be a more troublesome project.

I was originally only gonna fork it and change it for my own needs but thought that this could be a nifty little feature for other users as well.

I've corrected your PR comments and you can do what you want with it.

**Comment by HeadlessChild** [comment]
I would also think that if you are allowing something like Kerberos, "Basic Authentication" should also be supported. Mostly due to basic choices for the users and "Basic Authentication" is something that defiantly should be a viable choice.

Something like LDAP authentication is on a whole other level and should maybe be done outside of this container.

**Comment by kwk** [comment]
@HeadlessChild I would like merge you PR but I have an idea and would like to hear your opinion on it.

Right now, if you have Kerberos authentication enabled for the docker-registry-frontend, everything is protected and not only the manipulating requests.

You wrote:

> I limit everything except GET requests. So users without "Basic Authentication" should only be able to access GET requests. Users that authenticate with "Basic Authentication" are able to access all requests.

See the difference? ***All vs. everything except `GET` requests.***

What if we can create a common **switch** that works with all forms of authentication (currently Kerberos and Basic Auth) and which lets you protect either every request (`GET`,`PUT`,`DELETE`,...) or only the manipulating ones (all but `GET`)?

I think such a switch would need to go in and mess with the [apache-site.conf](https://github.com/kwk/docker-registry-frontend/blob/master/apache-site.conf) file.

I think of something like this (sketch from memory):

    <IfModule mod_auth_kerb.c>
        <Location />
           <IfDefine AUTH_ONLY_NON_GET>
              # Authentication required for every request types but GET.
              <LimitExcept GET>
                  # Configure authentication here
             </LimitExcept>
          <IfDefine>
           <IfDefine AUTH_ONLY_NON_GET>
              # Authentication required for every request types.
             # Configure authentication here
          <IfDefine>
        </Location>
    </IfModule>

Maybe this code can be cleaned up to no replicate the `# Configure authentication here` sections.

What do you think?

**Comment by Telmo** [comment]
Would it be possible to do namespace authentication using this approach? similar to how the Docker hub actually does it where you can only push to your own namespace and not to other people's namespace.

Authentication/Authorization is something that I am really interested on, as docker grows in my company I am finding myself in need for this type of authentication/authorization method.

**Comment by kwk** [comment]
@Telmo By now the docker-registry-frontend is supposed to be webfrontend and no authentication proxy for docker client. But if you want for instance want to allow a user to only delete tags or images under a certain namespace via the webfrontend, the answer is yes. Please open another issue for this.

**Pull request closed without merging**
