### PR TITLE
Change home page

### LINKED ISSUE #34: change to frontpage to be /repositories
It seems like there is one additional click all the time.. from / to /registry or is this configurable by now?

### PR DESCRIPTION
**Pull request by moimael**
Delete useless home page and make repository list the new home page

Fix #34

### CODE REVIEW

**Comment by moimael** [comment]
It's funny I had the exact same behaviour but the other way around. I think bower changed it back to dist on my machine, i will investigate.

**Comment by kwk** [comment]
If you remove the home page from the breadcrumbs menu I think there's no way to go from "Delete this tag or repository" back to the repository listing. The home page provided at least this. Maybe it makes more sense to make "home" the repository listing instead of removing home.

**Comment by moimael** [comment]
I did change the home in breadcrumbs with the repository listing, isnt it enough ?

**Comment by moimael** [comment]
Btw which release of jquery is installed on your system ? did you do bower update ? I have 2.1.4 and the bower.json specify:
    "main": "dist/jquery.js",

**Comment by kwk** [comment]
With 3807ecf1b802d02627dad9b6d5a2366bd1cf8df1 and 224d5d82ee50d0917a0d47cca228532beee51ff1 it is no longer possible to merge this PR. I'll try to get it working. Thank you so far. Closing this PR.

**Pull request closed without merging**
